export const demoProfile = {
  id: "demo-user",
  username: "alex-chen",
  name: "Alex Chen",
  email: "alex@techpulse.dev",
  avatarUrl: "https://avatars.githubusercontent.com/u/1?v=4",
  bio: "Full-stack engineer building AI products and developer tooling.",
  githubUrl: "https://github.com/alex-chen",
  publicRepos: 18,
  followers: 1280,
  following: 245,
};

export const demoRepositories = [
  {
    id: "repo-1",
    githubId: "1001",
    name: "techpulse-platform",
    fullName: "alex-chen/techpulse-platform",
    description: "AI-powered developer intelligence platform built with Next.js and Gemini.",
    url: "https://github.com/alex-chen/techpulse-platform",
    language: "TypeScript",
    stars: 412,
    forks: 61,
    watchers: 112,
    openIssues: 8,
    visibility: "public",
    defaultBranch: "main",
    owner: "alex-chen",
    createdAt: "2024-04-12T00:00:00.000Z",
    updatedAt: "2025-08-11T00:00:00.000Z",
    pushedAt: "2025-08-11T00:00:00.000Z",
  },
  {
    id: "repo-2",
    githubId: "1002",
    name: "edge-analytics",
    fullName: "alex-chen/edge-analytics",
    description: "Realtime data pipeline for telemetry and anomaly detection.",
    url: "https://github.com/alex-chen/edge-analytics",
    language: "Python",
    stars: 241,
    forks: 36,
    watchers: 74,
    openIssues: 5,
    visibility: "public",
    defaultBranch: "main",
    owner: "alex-chen",
    createdAt: "2023-11-01T00:00:00.000Z",
    updatedAt: "2025-08-09T00:00:00.000Z",
    pushedAt: "2025-08-09T00:00:00.000Z",
  },
  {
    id: "repo-3",
    githubId: "1003",
    name: "ui-system-kit",
    fullName: "alex-chen/ui-system-kit",
    description: "Reusable component system with design tokens and accessibility tooling.",
    url: "https://github.com/alex-chen/ui-system-kit",
    language: "TypeScript",
    stars: 298,
    forks: 44,
    watchers: 92,
    openIssues: 4,
    visibility: "public",
    defaultBranch: "main",
    owner: "alex-chen",
    createdAt: "2023-09-16T00:00:00.000Z",
    updatedAt: "2025-08-02T00:00:00.000Z",
    pushedAt: "2025-08-02T00:00:00.000Z",
  },
  {
    id: "repo-4",
    githubId: "1004",
    name: "infra-sentinel",
    fullName: "alex-chen/infra-sentinel",
    description: "Infrastructure health checks and platform observability tooling.",
    url: "https://github.com/alex-chen/infra-sentinel",
    language: "Go",
    stars: 171,
    forks: 27,
    watchers: 63,
    openIssues: 3,
    visibility: "public",
    defaultBranch: "main",
    owner: "alex-chen",
    createdAt: "2024-02-19T00:00:00.000Z",
    updatedAt: "2025-07-26T00:00:00.000Z",
    pushedAt: "2025-07-26T00:00:00.000Z",
  },
];

export const demoCommits = [
  {
    id: "commit-1",
    message: "Refine auth flow and cache design",
    author: "Alex Chen",
    url: "https://github.com/alex-chen/techpulse-platform/commit/1",
    createdAt: "2025-08-11T09:00:00.000Z",
    repository: "techpulse-platform",
  },
  {
    id: "commit-2",
    message: "Add telemetry normalization for streaming events",
    author: "Alex Chen",
    url: "https://github.com/alex-chen/edge-analytics/commit/2",
    createdAt: "2025-08-10T14:30:00.000Z",
    repository: "edge-analytics",
  },
  {
    id: "commit-3",
    message: "Improve dark-mode token contrast and motion timing",
    author: "Alex Chen",
    url: "https://github.com/alex-chen/ui-system-kit/commit/3",
    createdAt: "2025-08-08T16:15:00.000Z",
    repository: "ui-system-kit",
  },
];

export const demoNews = [
  {
    title: "Open-source AI coding agents are accelerating developer tooling for teams",
    description: "Teams are adopting agentic workflows for code review, onboarding, and release automation.",
    url: "https://news.ycombinator.com/item?id=43121910",
    source: "Hacker News",
    publishedAt: "2025-08-12T08:00:00.000Z",
    category: "AI",
  },
  {
    title: "Postgres performance improvements continue to reshape real-time analytics infrastructure",
    description: "Developers are leaning on managed database workloads with better observability and tuning guarantees.",
    url: "https://example.com/postgres-performance",
    source: "Tech Wire",
    publishedAt: "2025-08-11T14:00:00.000Z",
    category: "Cloud",
  },
  {
    title: "Next.js route caching patterns become standard for better frontend performance",
    description: "A growing set of teams are using route-level caching and server components to simplify developer UX.",
    url: "https://example.com/nextjs-caching",
    source: "Web Dev Daily",
    publishedAt: "2025-08-10T10:30:00.000Z",
    category: "Web",
  },
];

export const demoLearning = [
  {
    technology: "Advanced TypeScript",
    reason: "Your projects rely heavily on typed full-stack systems, so stronger type modeling will reduce production bugs.",
    skillLevel: "Intermediate",
    resources: ["TypeScript Deep Dive", "Effective TypeScript", "Practical Type Theory"],
    priority: "High",
  },
  {
    technology: "System Design",
    reason: "You are building platform-scale products with analytics and AI workflows, which benefits from solid architecture fundamentals.",
    skillLevel: "Advanced",
    resources: ["Designing Data-Intensive Applications", "System Design Interview"],
    priority: "High",
  },
  {
    technology: "Next.js Performance",
    reason: "Optimizing route data, rendering, and caching will improve the quality of your shipped product experiences.",
    skillLevel: "Intermediate",
    resources: ["Next.js Docs", "Vercel Performance Guide"],
    priority: "Medium",
  },
];

export const demoAnalysis = {
  summary: "The codebase demonstrates strong product thinking with a clear focus on developer experience and AI-assisted workflows. The architecture is centered around a modern Next.js app with clear separation between UI, server logic, and data access patterns.",
  strengths: [
    "Clear product scope and thoughtful developer-facing experience",
    "Strong integration of server-side data and UI layering",
    "Polished visual language and reusable component structure",
  ],
  weaknesses: [
    "Some features could benefit from more focused caching and stronger rate controls",
    "Testing coverage is still thin for edge-case scenarios",
    "Observability and error tracing could be more centralized",
  ],
  architecture: "A modular app with a dashboard, analytics, AI, and news surfaces, backed by a Prisma data layer and service-based API interfaces.",
  codeQuality: 88,
  maintainability: 86,
  security: 80,
  scalability: 82,
  technologies: ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "Tailwind CSS", "Gemini API"],
  improvements: [
    "Add explicit request-rate limiting and retry policies for AI integrations",
    "Introduce centralized API caching and stale-while-revalidate patterns",
    "Add end-to-end tests around auth and GitHub sync workflows",
  ],
  learningRecommendations: [
    "Deepen system design practice for distributed data services",
    "Improve instrumentation and distributed tracing across app routes",
    "Build stronger test automation for AI-powered flows",
  ],
};
